#!/bin/bash

# Used an article and associated git repo as guide and starting point.
# Article: https://www.altoros.com/blog/kubernetes-networking-writing-your-own-simple-cni-plug-in-with-bash/
# git: https://github.com/s-matyukevich/bash-cni-plugin/blob/master/bash-cni


exec 3>&1 # make stdout available as fd 3 for the result
exec &>> /var/log/nppnet-skel.log


# Parameters:
# CNI_COMMAND
# CNI_CONTAINERID
# CNI_NETNS
# CNI_IFNAME
# CNI_ARGS
# CNI_PATH

#echo "CNI command: $CNI_COMMAND" 
echo "CNI_COMMAND: $CNI_COMMAND, CNI_CONTAINERID: $CNI_CONTAINERID, CNI_NETNS: $CNI_NETNS, CNI_IFNAME: $CNI_IFNAME, CNI_ARGS: $CNI_ARGS, CNI_PATH: $CNI_PATH"

stdin=`cat /dev/stdin`
echo "stdin: $stdin"

# ADD, DEL, VERSION in 0.3.1 spec

case $CNI_COMMAND in
ADD)

   echo "Nothing to do - Add"
   ;;

DEL)

   echo "Nothing to do - DEL"

   ;;

VERSION)

echo '{
  "cniVersion": "0.3.1", 
  "supportedVersions": [ "0.3.0", "0.3.1" ] 
}' >&3

   ;;

esac


